#spring config
spring:
  application:
    name: wishlist
  config:
    import: configserver:http://localhost:8888
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

logging:
  level:
    web: DEBUG



