#spring config
spring:
  application:
    name: NEWSAPP-NEWS-PROVIDER
  config:
    import: configserver:http://localhost:8888

news-provider:
  third-party-endpoint: https://news67.p.rapidapi.com/v2/topic-search?languages=en&search=
  api-key: 15cf8c1829msh6512b6b75c04450p1a83b8jsn9a2c24e0cbc3
  host: news67.p.rapidapi.com