#spring config
spring:
  application:
    name: NEWSAPP-AUTH-SERVICE
  config:
    import: configserver:http://localhost:8888

token:
  signing:
    key: nvjlfbvjfkhgvaygtcygdyhgcghfggtcajggdhchvdfgbsgbfuygsyusb
